## define the telluric wavelength calibration parameters for each orders
import numpy as np

cal_param_nirspec = {
	'30':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'31':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'32':{'xcorr_range':40, 'outlier_rej':3., 	'pixel_range_start':10,	'pixel_range_end':-60 },
	'33':{'xcorr_range':25, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
	'34':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
	'35':{'xcorr_range':5, 	'outlier_rej':2., 	'pixel_range_start':10, 'pixel_range_end':-10},
	'36':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-50 },
	'37':{'xcorr_range':10, 'outlier_rej':2.5, 	'pixel_range_start':50, 'pixel_range_end':-20 },
	'38':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':50, 'pixel_range_end':-20 },
	'39':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':50, 'pixel_range_end':-20 },
	'55':{'xcorr_range':5, 	'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-90 },
	'56':{'xcorr_range':5, 	'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-30 },
	'57':{'xcorr_range':20, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'58':{'xcorr_range':15, 'outlier_rej':2., 	'pixel_range_start':0, 	'pixel_range_end':-30 },
	'59':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'60':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':5, 	'pixel_range_end':-5 },
	'61':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'62':{'xcorr_range':10, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'63':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'64':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'65':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':0, 	'pixel_range_end':-1 },
	'66':{'xcorr_range':15, 'outlier_rej':3., 	'pixel_range_start':10,	'pixel_range_end':-1 },
}

cal_param_igrins = {
	'71': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'72': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'73': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'74': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'75': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'76': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'77': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'78': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'79': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'80': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'81': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'82': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'83': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'84': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'85': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'86': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'87': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'88': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'89': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'90': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'91': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'92': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'93': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'94': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'95': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'96': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'97': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'98': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'99': {'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'100':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'101':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'102':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'103':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'104':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'105':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'106':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'107':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'108':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'109':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'110':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'111':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'112':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'113':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'114':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'115':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'116':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'117':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'118':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'119':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'120':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'121':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'122':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'123':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
	'124':{'xcorr_range':1.0, 'outlier_rej':2.5, 	'pixel_range_start':70, 	'pixel_range_end':-40},
}

